export const problemsData = {
  user_name: "",
  num_solved: 0,
  num_total: 2996,
  ac_easy: 0,
  ac_medium: 0,
  ac_hard: 0,
  stat_status_pairs: [
    {
      stat: {
        question_id: 3478,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Check if the Rectangle Corner Is Reachable",
        question__title_slug: "check-if-the-rectangle-corner-is-reachable",
        question__hide: false,
        total_acs: 6556,
        total_submitted: 24787,
        frontend_question_id: 3235,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 3,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },

    {
      stat: {
        question_id: 3363,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Most Frequent IDs",
        question__title_slug: "most-frequent-ids",
        question__hide: false,
        total_acs: 20810,
        total_submitted: 48967,
        frontend_question_id: 3092,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 2,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3362,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Find the Median of the Uniqueness Array",
        question__title_slug: "find-the-median-of-the-uniqueness-array",
        question__hide: false,
        total_acs: 6617,
        total_submitted: 23268,
        frontend_question_id: 3134,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 3,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3361,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title:
          "Latest Time You Can Obtain After Replacing Characters",
        question__title_slug:
          "latest-time-you-can-obtain-after-replacing-characters",
        question__hide: false,
        total_acs: 35661,
        total_submitted: 100503,
        frontend_question_id: 3114,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 1,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3360,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Minimum Deletions to Make String K-Special",
        question__title_slug: "minimum-deletions-to-make-string-k-special",
        question__hide: false,
        total_acs: 20615,
        total_submitted: 46926,
        frontend_question_id: 3085,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 2,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3359,
        question__article__live: true,
        question__article__slug: "linked-list-frequency",
        question__article__has_video_solution: false,
        question__title: "Linked List Frequency",
        question__title_slug: "linked-list-frequency",
        question__hide: false,
        total_acs: 11160,
        total_submitted: 12998,
        frontend_question_id: 3063,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 1,
      },
      paid_only: true,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3356,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Shortest Uncommon Substring in an Array",
        question__title_slug: "shortest-uncommon-substring-in-an-array",
        question__hide: false,
        total_acs: 24306,
        total_submitted: 52323,
        frontend_question_id: 3076,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 2,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3355,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Minimum Levels to Gain More Points",
        question__title_slug: "minimum-levels-to-gain-more-points",
        question__hide: false,
        total_acs: 23136,
        total_submitted: 57982,
        frontend_question_id: 3096,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 2,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3354,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title:
          "Replace Question Marks in String to Minimize Its Value",
        question__title_slug:
          "replace-question-marks-in-string-to-minimize-its-value",
        question__hide: false,
        total_acs: 14355,
        total_submitted: 52247,
        frontend_question_id: 3081,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 2,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3353,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Existence of a Substring in a String and Its Reverse",
        question__title_slug:
          "existence-of-a-substring-in-a-string-and-its-reverse",
        question__hide: false,
        total_acs: 47322,
        total_submitted: 71590,
        frontend_question_id: 3083,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 1,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3352,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Find Pattern in Infinite Stream II",
        question__title_slug: "find-pattern-in-infinite-stream-ii",
        question__hide: false,
        total_acs: 1005,
        total_submitted: 1443,
        frontend_question_id: 3037,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 3,
      },
      paid_only: true,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3351,
        question__article__live: true,
        question__article__slug: "maximize-happiness-of-selected-children",
        question__article__has_video_solution: false,
        question__title: "Maximize Happiness of Selected Children",
        question__title_slug: "maximize-happiness-of-selected-children",
        question__hide: false,
        total_acs: 176988,
        total_submitted: 322475,
        frontend_question_id: 3075,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 2,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3350,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Distribute Elements Into Two Arrays II",
        question__title_slug: "distribute-elements-into-two-arrays-ii",
        question__hide: false,
        total_acs: 10757,
        total_submitted: 39278,
        frontend_question_id: 3072,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 3,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3349,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Maximum Length Substring With Two Occurrences",
        question__title_slug: "maximum-length-substring-with-two-occurrences",
        question__hide: false,
        total_acs: 44316,
        total_submitted: 69489,
        frontend_question_id: 3090,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 1,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3348,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Minimum Cost Walk in Weighted Graph",
        question__title_slug: "minimum-cost-walk-in-weighted-graph",
        question__hide: false,
        total_acs: 12998,
        total_submitted: 28840,
        frontend_question_id: 3108,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 3,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3347,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title: "Distribute Elements Into Two Arrays I",
        question__title_slug: "distribute-elements-into-two-arrays-i",
        question__hide: false,
        total_acs: 46574,
        total_submitted: 64353,
        frontend_question_id: 3069,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 1,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 3346,
        question__article__live: null,
        question__article__slug: null,
        question__article__has_video_solution: null,
        question__title:
          "Lexicographically Smallest String After Operations With Constraint",
        question__title_slug:
          "lexicographically-smallest-string-after-operations-with-constraint",
        question__hide: false,
        total_acs: 26173,
        total_submitted: 41415,
        frontend_question_id: 3106,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 2,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
    {
      stat: {
        question_id: 26,
        question__article__live: true,
        question__article__slug: "remove-duplicates-from-sorted-array",
        question__article__has_video_solution: false,
        question__title: "Remove Duplicates from Sorted Array",
        question__title_slug: "remove-duplicates-from-sorted-array",
        question__hide: false,
        total_acs: 5368737,
        total_submitted: 9175707,
        frontend_question_id: 26,
        is_new_question: false,
      },
      status: null,
      difficulty: {
        level: 1,
      },
      paid_only: false,
      is_favor: false,
      frequency: 0,
      progress: 0,
    },
  ],
  frequency_high: 0,
  frequency_mid: 0,
  category_slug: "algorithms",
};
